2021-04-17 20:51:25,822 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-17 21:12:35,532 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-17 21:13:31,228 ERROR: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\log.py
	 Internal Server Error: /api/users/list/
Traceback (most recent call last):
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\rest_framework\views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\rest_framework\views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\rest_framework\views.py", line 476, in raise_uncaught_exception
    raise exc
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\rest_framework\views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "E:\Pycharm Project\WallAppPython-master\users\views.py", line 65, in post
    utils.send_email(subject="WELCOME!", recipient=[serializer.data['email']], body=email_html_message)
  File "E:\Pycharm Project\WallAppPython-master\utils.py", line 7, in send_email
    send_mail(
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\mail\__init__.py", line 60, in send_mail
    return mail.send()
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\mail\message.py", line 276, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\mail\backends\smtp.py", line 109, in send_messages
    sent = self._send(message)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\mail\backends\smtp.py", line 125, in _send
    self.connection.sendmail(from_email, recipients, message.as_bytes(linesep='\r\n'))
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\smtplib.py", line 869, in sendmail
    raise SMTPSenderRefused(code, resp, from_addr)
smtplib.SMTPSenderRefused: (530, b'5.7.0 Authentication Required. Learn more at\n5.7.0  https://support.google.com/mail/?p=WantAuthError h1sm8048470pgv.88 - gsmtp', 'webmaster@localhost')
2021-04-17 21:13:31,253 ERROR: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "POST /api/users/list/ HTTP/1.1" 500 18379
2021-04-17 21:15:03,130 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 E:\Pycharm Project\WallAppPython-master\wall_app\settings\settings.py changed, reloading.
2021-04-17 21:15:04,248 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-17 21:18:24,183 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 E:\Pycharm Project\WallAppPython-master\wall_app\settings\settings.py changed, reloading.
2021-04-17 21:18:31,008 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-17 21:21:29,656 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 E:\Pycharm Project\WallAppPython-master\wall_app\settings\settings.py changed, reloading.
2021-04-17 21:21:30,944 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-17 21:22:05,837 WARNING: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\log.py
	 Bad Request: /api/users/list/
2021-04-17 21:22:05,838 WARNING: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "POST /api/users/list/ HTTP/1.1" 400 76
2021-04-17 21:22:40,683 ERROR: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\log.py
	 Internal Server Error: /api/users/list/
Traceback (most recent call last):
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\rest_framework\views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\rest_framework\views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\rest_framework\views.py", line 476, in raise_uncaught_exception
    raise exc
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\rest_framework\views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "E:\Pycharm Project\WallAppPython-master\users\views.py", line 65, in post
    utils.send_email(subject="WELCOME!", recipient=[serializer.data['email']], body=email_html_message)
  File "E:\Pycharm Project\WallAppPython-master\utils.py", line 7, in send_email
    send_mail(
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\mail\__init__.py", line 60, in send_mail
    return mail.send()
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\mail\message.py", line 276, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\mail\backends\smtp.py", line 102, in send_messages
    new_conn_created = self.open()
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\mail\backends\smtp.py", line 69, in open
    self.connection.login(self.username, self.password)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\smtplib.py", line 732, in login
    raise last_exception
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\smtplib.py", line 721, in login
    (code, resp) = self.auth(
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\smtplib.py", line 644, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials v2sm8722280pjg.34 - gsmtp')
2021-04-17 21:22:40,686 ERROR: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "POST /api/users/list/ HTTP/1.1" 500 18616
2021-04-17 21:23:11,922 WARNING: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\log.py
	 Bad Request: /api/users/list/
2021-04-17 21:23:11,923 WARNING: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "POST /api/users/list/ HTTP/1.1" 400 76
2021-04-17 21:23:18,215 WARNING: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\log.py
	 Bad Request: /api/users/list/
2021-04-17 21:23:18,216 WARNING: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "POST /api/users/list/ HTTP/1.1" 400 71
2021-04-17 21:25:09,007 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-17 21:25:26,784 ERROR: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\log.py
	 Internal Server Error: /api/users/list/
Traceback (most recent call last):
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\rest_framework\views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\rest_framework\views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\rest_framework\views.py", line 476, in raise_uncaught_exception
    raise exc
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\rest_framework\views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "E:\Pycharm Project\WallAppPython-master\users\views.py", line 65, in post
    utils.send_email(subject="WELCOME!", recipient=[serializer.data['email']], body=email_html_message)
  File "E:\Pycharm Project\WallAppPython-master\utils.py", line 7, in send_email
    send_mail(
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\mail\__init__.py", line 60, in send_mail
    return mail.send()
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\mail\message.py", line 276, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\mail\backends\smtp.py", line 102, in send_messages
    new_conn_created = self.open()
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\mail\backends\smtp.py", line 69, in open
    self.connection.login(self.username, self.password)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\smtplib.py", line 732, in login
    raise last_exception
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\smtplib.py", line 721, in login
    (code, resp) = self.auth(
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\smtplib.py", line 644, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials s21sm9260061pjr.52 - gsmtp')
2021-04-17 21:25:26,788 ERROR: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "POST /api/users/list/ HTTP/1.1" 500 18617
2021-04-17 21:29:23,638 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-17 21:29:45,753 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "POST /api/users/list/ HTTP/1.1" 201 276
2021-04-17 21:31:04,611 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "POST /api/token/ HTTP/1.1" 200 469
2021-04-17 21:31:57,884 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "PUT /api/users/details/1/ HTTP/1.1" 201 288
2021-04-17 21:34:10,623 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "GET /api/users/details/1/ HTTP/1.1" 200 290
2021-04-17 21:34:59,947 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "POST /api/wall/walls/list/ HTTP/1.1" 201 248
2021-04-17 21:35:24,026 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "GET /api/wall/walls/list/ HTTP/1.1" 200 312
2021-04-17 21:35:38,695 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "GET /api/wall/walls/details/1/ HTTP/1.1" 200 250
2021-04-18 13:41:05,554 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-18 13:41:23,259 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "POST /api/users/list/ HTTP/1.1" 201 276
2021-04-18 13:41:37,644 WARNING: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\log.py
	 Unauthorized: /api/wall/walls/list/
2021-04-18 13:41:37,645 WARNING: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "POST /api/wall/walls/list/ HTTP/1.1" 401 183
2021-04-18 13:41:51,658 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "POST /api/token/ HTTP/1.1" 200 469
2021-04-18 13:41:57,030 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "POST /api/wall/walls/list/ HTTP/1.1" 201 248
2021-04-18 13:42:09,823 WARNING: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\log.py
	 Bad Request: /api/wall/comment/list/
2021-04-18 13:42:09,824 WARNING: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "POST /api/wall/comment/list/ HTTP/1.1" 400 76
2021-04-18 13:42:20,901 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "POST /api/wall/comment/list/ HTTP/1.1" 201 237
2021-04-18 13:42:30,394 ERROR: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\log.py
	 Internal Server Error: /api/wall/likes/1/
Traceback (most recent call last):
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\rest_framework\views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\rest_framework\views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\rest_framework\views.py", line 476, in raise_uncaught_exception
    raise exc
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\rest_framework\views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "E:\Pycharm Project\WallAppPython-master\wall\views.py", line 267, in get
    if request.user in wall.likes.users.all():
AttributeError: 'Wall' object has no attribute 'likes'
2021-04-18 13:42:30,396 ERROR: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "GET /api/wall/likes/1/ HTTP/1.1" 500 17179
2021-04-18 14:30:45,224 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-18 15:50:17,243 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-18 15:50:48,396 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "POST /api/users/list/ HTTP/1.1" 201 276
2021-04-18 15:51:00,365 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "POST /api/token/ HTTP/1.1" 200 469
2021-04-18 15:51:10,373 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "POST /api/wall/walls/list/ HTTP/1.1" 201 248
2021-04-18 15:51:21,088 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "POST /api/wall/comment/list/ HTTP/1.1" 201 237
2021-04-18 15:51:34,771 ERROR: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\log.py
	 Internal Server Error: /api/wall/likes/1/
Traceback (most recent call last):
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\rest_framework\views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\rest_framework\views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\rest_framework\views.py", line 476, in raise_uncaught_exception
    raise exc
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\rest_framework\views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "E:\Pycharm Project\WallAppPython-master\wall\views.py", line 267, in get
    if request.user in wall.likes.users.all():
AttributeError: 'Wall' object has no attribute 'likes'
2021-04-18 15:51:34,774 ERROR: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "GET /api/wall/likes/1/ HTTP/1.1" 500 17179
2021-04-18 16:08:53,023 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 E:\Pycharm Project\WallAppPython-master\wall\models.py changed, reloading.
2021-04-18 16:08:54,168 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-18 16:08:57,080 ERROR: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\log.py
	 Internal Server Error: /api/wall/likes/1/
Traceback (most recent call last):
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\rest_framework\views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\rest_framework\views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\rest_framework\views.py", line 476, in raise_uncaught_exception
    raise exc
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\rest_framework\views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "E:\Pycharm Project\WallAppPython-master\wall\views.py", line 267, in get
    if request.user in wall.likes.users.all():
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\db\models\fields\related_descriptors.py", line 420, in __get__
    raise self.RelatedObjectDoesNotExist(
wall.models.Wall.likes.RelatedObjectDoesNotExist: Wall has no likes.
2021-04-18 16:08:57,082 ERROR: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "GET /api/wall/likes/1/ HTTP/1.1" 500 17344
2021-04-18 16:17:16,407 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 E:\Pycharm Project\WallAppPython-master\wall\views.py changed, reloading.
2021-04-18 16:17:17,817 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-18 16:19:01,994 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 E:\Pycharm Project\WallAppPython-master\wall\views.py changed, reloading.
2021-04-18 16:19:02,985 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-18 16:19:06,129 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 E:\Pycharm Project\WallAppPython-master\wall\views.py changed, reloading.
2021-04-18 16:19:07,144 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-18 16:19:13,068 ERROR: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\log.py
	 Internal Server Error: /api/wall/likes/1/
Traceback (most recent call last):
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\rest_framework\views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\rest_framework\views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\rest_framework\views.py", line 476, in raise_uncaught_exception
    raise exc
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\rest_framework\views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "E:\Pycharm Project\WallAppPython-master\wall\views.py", line 267, in get
    if wall.likes:
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\db\models\fields\related_descriptors.py", line 420, in __get__
    raise self.RelatedObjectDoesNotExist(
wall.models.Wall.likes.RelatedObjectDoesNotExist: Wall has no likes.
2021-04-18 16:19:13,070 ERROR: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "GET /api/wall/likes/1/ HTTP/1.1" 500 17316
2021-04-18 16:20:57,392 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 E:\Pycharm Project\WallAppPython-master\wall\views.py changed, reloading.
2021-04-18 16:20:59,630 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-18 16:22:23,831 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 E:\Pycharm Project\WallAppPython-master\wall\views.py changed, reloading.
2021-04-18 16:22:25,079 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-18 16:22:30,136 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "GET /api/wall/likes/1/ HTTP/1.1" 200 42
2021-04-18 16:23:07,665 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 E:\Pycharm Project\WallAppPython-master\wall\views.py changed, reloading.
2021-04-18 16:23:08,668 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-18 16:23:12,502 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "GET /api/wall/likes/1/ HTTP/1.1" 200 42
2021-04-18 16:23:22,503 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 E:\Pycharm Project\WallAppPython-master\wall\views.py changed, reloading.
2021-04-18 16:23:23,505 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-18 16:23:29,554 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-18 16:23:35,406 ERROR: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\log.py
	 Internal Server Error: /api/wall/likes/1/
Traceback (most recent call last):
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\rest_framework\views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\rest_framework\views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\rest_framework\views.py", line 476, in raise_uncaught_exception
    raise exc
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\rest_framework\views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "E:\Pycharm Project\WallAppPython-master\wall\views.py", line 275, in get
    wall.dis_likes.users.remove(request.user)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\db\models\fields\related_descriptors.py", line 420, in __get__
    raise self.RelatedObjectDoesNotExist(
wall.models.Wall.dis_likes.RelatedObjectDoesNotExist: Wall has no dis_likes.
2021-04-18 16:23:35,408 ERROR: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "GET /api/wall/likes/1/ HTTP/1.1" 500 17351
2021-04-18 16:24:08,943 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 E:\Pycharm Project\WallAppPython-master\wall\views.py changed, reloading.
2021-04-18 16:24:09,946 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-18 16:24:20,580 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "GET /api/wall/likes/1/ HTTP/1.1" 200 42
2021-04-18 16:24:39,016 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "GET /api/wall/likes/1/ HTTP/1.1" 200 42
2021-04-18 16:26:07,991 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 E:\Pycharm Project\WallAppPython-master\wall\views.py changed, reloading.
2021-04-18 16:26:09,010 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-18 16:28:41,357 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 E:\Pycharm Project\WallAppPython-master\wall\views.py changed, reloading.
2021-04-18 16:28:42,463 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-18 16:30:34,498 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 E:\Pycharm Project\WallAppPython-master\wall\serializers.py changed, reloading.
2021-04-18 16:30:35,605 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-18 16:31:00,791 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "GET /api/wall/likes/1/ HTTP/1.1" 200 42
2021-04-18 16:35:16,319 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 E:\Pycharm Project\WallAppPython-master\wall\views.py changed, reloading.
2021-04-18 16:35:17,341 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-18 16:35:23,419 ERROR: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\log.py
	 Internal Server Error: /api/wall/likes/1/
Traceback (most recent call last):
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\rest_framework\views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\rest_framework\views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\rest_framework\views.py", line 476, in raise_uncaught_exception
    raise exc
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\rest_framework\views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "E:\Pycharm Project\WallAppPython-master\wall\views.py", line 275, in get
    wall.dis_likes.users.remove(request.user)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\db\models\fields\related_descriptors.py", line 420, in __get__
    raise self.RelatedObjectDoesNotExist(
wall.models.Wall.dis_likes.RelatedObjectDoesNotExist: Wall has no dis_likes.
2021-04-18 16:35:23,422 ERROR: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "GET /api/wall/likes/1/ HTTP/1.1" 500 17351
2021-04-18 16:35:27,250 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "GET /api/wall/likes/1/ HTTP/1.1" 200 42
2021-04-18 16:36:23,936 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-18 16:36:43,286 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "POST /api/users/list/ HTTP/1.1" 201 276
2021-04-18 16:36:48,807 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "POST /api/token/ HTTP/1.1" 200 469
2021-04-18 16:36:57,182 ERROR: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\log.py
	 Internal Server Error: /api/wall/walls/list/
Traceback (most recent call last):
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 396, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: FOREIGN KEY constraint failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\rest_framework\views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\rest_framework\views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\rest_framework\views.py", line 476, in raise_uncaught_exception
    raise exc
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\rest_framework\views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "E:\Pycharm Project\WallAppPython-master\wall\views.py", line 69, in post
    serializer.save()
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\rest_framework\serializers.py", line 212, in save
    self.instance = self.create(validated_data)
  File "E:\Pycharm Project\WallAppPython-master\wall\serializers.py", line 65, in create
    Like.objects.create(wall=wall)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\db\models\query.py", line 433, in create
    obj.save(force_insert=True, using=self.db)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\db\models\base.py", line 745, in save
    self.save_base(using=using, force_insert=force_insert,
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\db\models\base.py", line 782, in save_base
    updated = self._save_table(
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\db\models\base.py", line 887, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\db\models\base.py", line 924, in _do_insert
    return manager._insert(
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\db\models\query.py", line 1204, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1392, in execute_sql
    cursor.execute(sql, params)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\db\backends\utils.py", line 100, in execute
    return super().execute(sql, params)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\db\backends\utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\db\backends\utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 396, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: FOREIGN KEY constraint failed
2021-04-18 16:36:57,189 ERROR: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "POST /api/wall/walls/list/ HTTP/1.1" 500 20836
2021-04-18 16:37:11,590 WARNING: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\log.py
	 Bad Request: /api/wall/walls/list/
2021-04-18 16:37:11,590 WARNING: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "POST /api/wall/walls/list/ HTTP/1.1" 400 83
2021-04-18 16:38:25,902 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-18 16:38:46,798 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "POST /api/users/list/ HTTP/1.1" 201 276
2021-04-18 16:38:55,486 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "POST /api/token/ HTTP/1.1" 200 469
2021-04-18 16:39:13,052 ERROR: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\log.py
	 Internal Server Error: /api/wall/walls/list/
Traceback (most recent call last):
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 396, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: FOREIGN KEY constraint failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\rest_framework\views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\rest_framework\views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\rest_framework\views.py", line 476, in raise_uncaught_exception
    raise exc
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\rest_framework\views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "E:\Pycharm Project\WallAppPython-master\wall\views.py", line 69, in post
    serializer.save()
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\rest_framework\serializers.py", line 212, in save
    self.instance = self.create(validated_data)
  File "E:\Pycharm Project\WallAppPython-master\wall\serializers.py", line 65, in create
    Like.objects.create(wall=wall)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\db\models\query.py", line 433, in create
    obj.save(force_insert=True, using=self.db)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\db\models\base.py", line 745, in save
    self.save_base(using=using, force_insert=force_insert,
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\db\models\base.py", line 782, in save_base
    updated = self._save_table(
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\db\models\base.py", line 887, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\db\models\base.py", line 924, in _do_insert
    return manager._insert(
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\db\models\query.py", line 1204, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1392, in execute_sql
    cursor.execute(sql, params)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\db\backends\utils.py", line 100, in execute
    return super().execute(sql, params)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\db\backends\utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\db\backends\utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 396, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: FOREIGN KEY constraint failed
2021-04-18 16:39:13,059 ERROR: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "POST /api/wall/walls/list/ HTTP/1.1" 500 20836
2021-04-18 16:40:25,104 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 E:\Pycharm Project\WallAppPython-master\wall\serializers.py changed, reloading.
2021-04-18 16:40:26,129 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-18 16:41:53,604 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-18 16:42:09,884 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "POST /api/users/list/ HTTP/1.1" 201 276
2021-04-18 16:42:13,444 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "POST /api/token/ HTTP/1.1" 200 469
2021-04-18 16:42:21,651 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "POST /api/wall/walls/list/ HTTP/1.1" 201 248
2021-04-18 16:43:10,778 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 E:\Pycharm Project\WallAppPython-master\wall\models.py changed, reloading.
2021-04-18 16:43:11,779 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-18 16:43:28,614 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 E:\Pycharm Project\WallAppPython-master\wall\models.py changed, reloading.
2021-04-18 16:43:29,681 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-18 16:45:00,683 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-18 16:45:15,124 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 E:\Pycharm Project\WallAppPython-master\wall\serializers.py changed, reloading.
2021-04-18 16:45:16,160 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-18 16:45:51,450 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "POST /api/users/list/ HTTP/1.1" 201 276
2021-04-18 16:45:59,591 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "POST /api/token/ HTTP/1.1" 200 469
2021-04-18 16:46:05,014 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "POST /api/wall/walls/list/ HTTP/1.1" 201 248
2021-04-18 16:46:17,528 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "GET /api/wall/likes/1/ HTTP/1.1" 200 42
2021-04-18 16:47:37,313 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 E:\Pycharm Project\WallAppPython-master\wall\views.py changed, reloading.
2021-04-18 16:47:38,422 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-18 16:47:41,177 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "GET /api/wall/likes/1/ HTTP/1.1" 200 42
2021-04-18 16:48:10,161 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 E:\Pycharm Project\WallAppPython-master\wall\views.py changed, reloading.
2021-04-18 16:48:11,248 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-18 16:48:40,939 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-18 16:48:56,426 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "GET /api/wall/likes/1/ HTTP/1.1" 200 42
2021-04-18 16:49:11,910 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "GET /api/wall/likes/1/ HTTP/1.1" 200 42
2021-04-18 16:49:25,678 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "GET /api/wall/dislikes/1/ HTTP/1.1" 200 45
2021-04-18 16:49:52,656 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "GET /api/wall/dislikes/1/ HTTP/1.1" 200 45
2021-04-18 16:55:29,256 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-18 16:55:44,676 ERROR: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\log.py
	 Internal Server Error: /api/wall/walls/details/1/
Traceback (most recent call last):
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\rest_framework\views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\rest_framework\views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\rest_framework\views.py", line 476, in raise_uncaught_exception
    raise exc
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\rest_framework\views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "E:\Pycharm Project\WallAppPython-master\wall\views.py", line 102, in get
    api_response = ApiResponse(status=1, data=serializer.data, message=constants.GET_WALL_SUCCESS,
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\rest_framework\serializers.py", line 562, in data
    ret = super().data
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\rest_framework\serializers.py", line 260, in data
    self._data = self.to_representation(self.instance)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\rest_framework\serializers.py", line 514, in to_representation
    for field in fields:
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\rest_framework\serializers.py", line 375, in _readable_fields
    for field in self.fields.values():
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\rest_framework\serializers.py", line 363, in fields
    for key, value in self.get_fields().items():
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\rest_framework\serializers.py", line 1038, in get_fields
    field_names = self.get_field_names(declared_fields, info)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\rest_framework\serializers.py", line 1134, in get_field_names
    assert field_name in fields, (
AssertionError: The field 'likes' was declared on serializer WallSerializer, but has not been included in the 'fields' option.
2021-04-18 16:55:44,679 ERROR: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "GET /api/wall/walls/details/1/ HTTP/1.1" 500 18541
2021-04-18 16:56:27,495 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 E:\Pycharm Project\WallAppPython-master\wall\serializers.py changed, reloading.
2021-04-18 16:56:28,557 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-18 16:56:29,980 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "GET /api/wall/walls/details/1/ HTTP/1.1" 200 274
2021-04-18 16:56:39,723 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "GET /api/wall/likes/1/ HTTP/1.1" 200 42
2021-04-18 16:56:59,824 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "GET /api/wall/walls/details/1/ HTTP/1.1" 200 274
2021-04-18 16:57:25,990 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "GET /api/wall/dislikes/1/ HTTP/1.1" 200 45
2021-04-18 16:57:43,562 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "GET /api/wall/walls/details/1/ HTTP/1.1" 200 274
2021-04-18 17:02:42,669 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "GET /api/wall/likes/1/ HTTP/1.1" 200 42
2021-04-18 17:02:59,120 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "GET /api/wall/walls/details/1/ HTTP/1.1" 200 274
2021-04-18 17:04:12,807 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "POST /api/users/list/ HTTP/1.1" 201 269
2021-04-18 17:04:28,195 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "POST /api/token/ HTTP/1.1" 200 469
2021-04-18 17:04:39,361 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "GET /api/wall/walls/details/1/ HTTP/1.1" 200 274
2021-04-18 17:04:47,511 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "GET /api/wall/likes/1/ HTTP/1.1" 200 42
2021-04-18 17:04:52,071 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "GET /api/wall/walls/details/1/ HTTP/1.1" 200 274
2021-04-18 17:05:16,346 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "GET /api/wall/likes/1/ HTTP/1.1" 200 42
2021-04-18 17:05:21,442 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "GET /api/wall/walls/details/1/ HTTP/1.1" 200 274
2021-04-18 17:06:33,475 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "POST /api/token/ HTTP/1.1" 200 470
2021-04-18 17:06:41,514 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "GET /api/wall/walls/details/1/ HTTP/1.1" 200 274
2021-04-18 17:06:53,430 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "GET /api/wall/likes/1/ HTTP/1.1" 200 42
2021-04-18 17:06:57,315 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "GET /api/wall/walls/details/1/ HTTP/1.1" 200 274
2021-04-19 13:41:31,946 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-19 13:42:01,435 ERROR: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\log.py
	 Internal Server Error: /api/users/list/
Traceback (most recent call last):
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\rest_framework\views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\rest_framework\views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\rest_framework\views.py", line 476, in raise_uncaught_exception
    raise exc
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\rest_framework\views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\user\Desktop\WallAppPython\users\views.py", line 89, in post
    utils.send_email(subject="WELCOME!", recipient=[serializer.data['email']], body=email_html_message)
  File "C:\Users\user\Desktop\WallAppPython\utils.py", line 7, in send_email
    send_mail(
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\mail\__init__.py", line 60, in send_mail
    return mail.send()
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\mail\message.py", line 276, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\mail\backends\smtp.py", line 102, in send_messages
    new_conn_created = self.open()
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\mail\backends\smtp.py", line 69, in open
    self.connection.login(self.username, self.password)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\smtplib.py", line 732, in login
    raise last_exception
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\smtplib.py", line 721, in login
    (code, resp) = self.auth(
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\smtplib.py", line 644, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials v2sm13193817pjg.34 - gsmtp')
2021-04-19 13:42:01,437 ERROR: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "POST /api/users/list/ HTTP/1.1" 500 18578
2021-04-19 13:43:14,580 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 C:\Users\user\Desktop\WallAppPython\wall_app\settings\settings.py changed, reloading.
2021-04-19 13:43:15,625 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-19 13:43:46,014 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-19 13:44:13,800 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-19 13:44:26,428 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "POST /api/users/list/ HTTP/1.1" 201 263
2021-04-19 13:46:04,203 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 C:\Users\user\Desktop\WallAppPython\users\views.py changed, reloading.
2021-04-19 13:46:05,404 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-19 13:46:40,641 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "POST /api/users/list/ HTTP/1.1" 201 265
2021-04-19 13:47:31,780 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 C:\Users\user\Desktop\WallAppPython\users\views.py changed, reloading.
2021-04-19 13:47:32,762 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-19 14:12:13,212 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 C:\Users\user\Desktop\WallAppPython\users\views.py changed, reloading.
2021-04-19 14:12:14,598 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-19 14:13:29,660 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 C:\Users\user\Desktop\WallAppPython\users\views.py changed, reloading.
2021-04-19 14:13:30,698 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-19 14:15:36,295 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 C:\Users\user\Desktop\WallAppPython\users\views.py changed, reloading.
2021-04-19 14:15:37,379 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-19 14:16:14,435 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 C:\Users\user\Desktop\WallAppPython\users\views.py changed, reloading.
2021-04-19 14:16:15,455 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-19 14:16:52,188 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 C:\Users\user\Desktop\WallAppPython\users\views.py changed, reloading.
2021-04-19 14:16:53,281 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-19 14:17:10,328 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 C:\Users\user\Desktop\WallAppPython\users\views.py changed, reloading.
2021-04-19 14:17:11,342 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-19 14:17:54,679 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 C:\Users\user\Desktop\WallAppPython\users\views.py changed, reloading.
2021-04-19 14:17:55,738 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-19 14:18:06,171 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 C:\Users\user\Desktop\WallAppPython\users\views.py changed, reloading.
2021-04-19 14:18:07,173 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-19 14:19:07,459 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 C:\Users\user\Desktop\WallAppPython\users\views.py changed, reloading.
2021-04-19 14:19:08,499 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-19 14:20:51,774 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 C:\Users\user\Desktop\WallAppPython\constants.py changed, reloading.
2021-04-19 14:20:52,837 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-19 14:22:32,668 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 C:\Users\user\Desktop\WallAppPython\constants.py changed, reloading.
2021-04-19 14:22:33,690 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-19 14:23:32,224 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 C:\Users\user\Desktop\WallAppPython\users\views.py changed, reloading.
2021-04-19 14:23:33,307 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-19 14:26:29,017 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 C:\Users\user\Desktop\WallAppPython\users\views.py changed, reloading.
2021-04-19 14:26:30,374 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-19 14:26:55,367 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 C:\Users\user\Desktop\WallAppPython\users\views.py changed, reloading.
2021-04-19 14:26:56,452 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-19 14:29:10,214 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 C:\Users\user\Desktop\WallAppPython\users\views.py changed, reloading.
2021-04-19 14:29:11,317 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-19 14:32:02,085 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 C:\Users\user\Desktop\WallAppPython\users\views.py changed, reloading.
2021-04-19 14:32:03,141 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-19 14:32:48,063 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 C:\Users\user\Desktop\WallAppPython\users\views.py changed, reloading.
2021-04-19 14:32:49,135 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-19 14:33:06,576 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 C:\Users\user\Desktop\WallAppPython\users\views.py changed, reloading.
2021-04-19 14:33:07,604 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-19 14:33:26,413 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 C:\Users\user\Desktop\WallAppPython\users\views.py changed, reloading.
2021-04-19 14:33:27,664 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-19 14:33:46,649 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 C:\Users\user\Desktop\WallAppPython\users\views.py changed, reloading.
2021-04-19 14:33:47,849 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-19 14:36:48,560 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 C:\Users\user\Desktop\WallAppPython\users\views.py changed, reloading.
2021-04-19 14:36:49,602 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-19 14:39:09,205 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 C:\Users\user\Desktop\WallAppPython\users\views.py changed, reloading.
2021-04-19 14:39:10,442 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-19 14:39:40,870 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 C:\Users\user\Desktop\WallAppPython\users\views.py changed, reloading.
2021-04-19 14:39:41,864 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-19 14:41:05,195 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 C:\Users\user\Desktop\WallAppPython\users\views.py changed, reloading.
2021-04-19 14:41:06,194 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-19 14:43:02,832 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 C:\Users\user\Desktop\WallAppPython\users\models.py changed, reloading.
2021-04-19 14:43:03,967 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-19 14:43:57,595 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 C:\Users\user\Desktop\WallAppPython\users\models.py changed, reloading.
2021-04-19 14:43:58,660 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-19 15:45:46,401 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-19 15:47:19,232 ERROR: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\log.py
	 Internal Server Error: /api/users/list/
Traceback (most recent call last):
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 396, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: table users_user has no column named is_holiday

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\rest_framework\views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\rest_framework\views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\rest_framework\views.py", line 476, in raise_uncaught_exception
    raise exc
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\rest_framework\views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\user\Desktop\WallAppPython\users\views.py", line 81, in post
    serializer.save()
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\rest_framework\serializers.py", line 212, in save
    self.instance = self.create(validated_data)
  File "C:\Users\user\Desktop\WallAppPython\users\serializers.py", line 19, in create
    user = User.objects.create_user(**validated_data)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\contrib\auth\models.py", line 147, in create_user
    return self._create_user(username, email, password, **extra_fields)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\contrib\auth\models.py", line 141, in _create_user
    user.save(using=self._db)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\contrib\auth\base_user.py", line 66, in save
    super().save(*args, **kwargs)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\db\models\base.py", line 745, in save
    self.save_base(using=using, force_insert=force_insert,
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\db\models\base.py", line 782, in save_base
    updated = self._save_table(
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\db\models\base.py", line 887, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\db\models\base.py", line 924, in _do_insert
    return manager._insert(
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\db\models\query.py", line 1204, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1392, in execute_sql
    cursor.execute(sql, params)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\db\backends\utils.py", line 100, in execute
    return super().execute(sql, params)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\db\backends\utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\db\backends\utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 396, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: table users_user has no column named is_holiday
2021-04-19 15:47:19,239 ERROR: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "POST /api/users/list/ HTTP/1.1" 500 20991
2021-04-19 16:01:07,787 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-19 16:01:27,953 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "POST /api/users/list/ HTTP/1.1" 201 303
2021-04-19 16:02:31,388 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-19 16:02:59,614 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "POST /api/users/list/ HTTP/1.1" 201 305
2021-04-19 16:04:05,500 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 C:\Users\user\Desktop\WallAppPython\users\views.py changed, reloading.
2021-04-19 16:04:06,533 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-19 16:04:27,726 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "POST /api/users/list/ HTTP/1.1" 201 305
2021-04-19 16:04:47,530 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 C:\Users\user\Desktop\WallAppPython\users\views.py changed, reloading.
2021-04-19 16:04:48,711 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-19 16:06:12,368 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 C:\Users\user\Desktop\WallAppPython\users\views.py changed, reloading.
2021-04-19 16:06:13,389 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-19 16:06:44,615 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "POST /api/users/list/ HTTP/1.1" 201 304
2021-04-19 16:07:59,455 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 C:\Users\user\Desktop\WallAppPython\users\views.py changed, reloading.
2021-04-19 16:08:00,707 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-19 16:08:10,122 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 C:\Users\user\Desktop\WallAppPython\users\views.py changed, reloading.
2021-04-19 16:08:11,190 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-19 16:08:44,621 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 C:\Users\user\Desktop\WallAppPython\users\views.py changed, reloading.
2021-04-19 16:08:45,695 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-19 16:09:23,585 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "POST /api/users/list/ HTTP/1.1" 201 304
2021-04-19 16:12:12,180 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 C:\Users\user\Desktop\WallAppPython\users\views.py changed, reloading.
2021-04-19 16:12:13,262 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-19 16:12:31,402 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 C:\Users\user\Desktop\WallAppPython\users\views.py changed, reloading.
2021-04-19 16:12:32,409 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-19 16:12:55,103 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "POST /api/users/list/ HTTP/1.1" 201 305
2021-04-19 16:13:40,199 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 C:\Users\user\Desktop\WallAppPython\users\views.py changed, reloading.
2021-04-19 16:13:41,276 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-19 16:15:42,095 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 C:\Users\user\Desktop\WallAppPython\users\views.py changed, reloading.
2021-04-19 16:15:43,208 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-19 16:16:07,296 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "POST /api/users/list/ HTTP/1.1" 201 305
2021-04-19 16:16:45,356 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 C:\Users\user\Desktop\WallAppPython\users\views.py changed, reloading.
2021-04-19 16:16:46,424 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-19 16:20:14,521 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 C:\Users\user\Desktop\WallAppPython\users\models.py changed, reloading.
2021-04-19 16:20:15,531 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-19 16:20:43,146 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 C:\Users\user\Desktop\WallAppPython\users\models.py changed, reloading.
2021-04-19 16:20:44,238 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-19 16:21:56,307 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 C:\Users\user\Desktop\WallAppPython\users\views.py changed, reloading.
2021-04-19 16:21:57,395 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-19 16:22:03,982 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 C:\Users\user\Desktop\WallAppPython\users\views.py changed, reloading.
2021-04-19 16:22:04,973 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-19 16:22:27,577 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 C:\Users\user\Desktop\WallAppPython\users\views.py changed, reloading.
2021-04-19 16:22:28,628 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-19 16:25:18,283 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 C:\Users\user\Desktop\WallAppPython\users\serializers.py changed, reloading.
2021-04-19 16:25:19,283 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-19 16:25:32,262 ERROR: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\log.py
	 Internal Server Error: /api/users/list/
Traceback (most recent call last):
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 396, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: table users_user has no column named geolocation_data

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\rest_framework\views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\rest_framework\views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\rest_framework\views.py", line 476, in raise_uncaught_exception
    raise exc
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\rest_framework\views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\user\Desktop\WallAppPython\users\views.py", line 83, in post
    serializer.save(is_holiday=holiday_flag, holiday_details=holiday_details, geolocation_data=geolocation_data)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\rest_framework\serializers.py", line 212, in save
    self.instance = self.create(validated_data)
  File "C:\Users\user\Desktop\WallAppPython\users\serializers.py", line 19, in create
    user = User.objects.create_user(**validated_data)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\contrib\auth\models.py", line 147, in create_user
    return self._create_user(username, email, password, **extra_fields)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\contrib\auth\models.py", line 141, in _create_user
    user.save(using=self._db)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\contrib\auth\base_user.py", line 66, in save
    super().save(*args, **kwargs)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\db\models\base.py", line 745, in save
    self.save_base(using=using, force_insert=force_insert,
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\db\models\base.py", line 782, in save_base
    updated = self._save_table(
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\db\models\base.py", line 887, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\db\models\base.py", line 924, in _do_insert
    return manager._insert(
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\db\models\query.py", line 1204, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1392, in execute_sql
    cursor.execute(sql, params)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\db\backends\utils.py", line 100, in execute
    return super().execute(sql, params)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\db\backends\utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\db\backends\utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\db\utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\db\backends\utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\db\backends\sqlite3\base.py", line 396, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: table users_user has no column named geolocation_data
2021-04-19 16:25:32,269 ERROR: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "POST /api/users/list/ HTTP/1.1" 500 21100
2021-04-19 16:28:32,830 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-19 16:28:54,104 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "POST /api/users/list/ HTTP/1.1" 201 1324
2021-04-19 16:30:14,757 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 C:\Users\user\Desktop\WallAppPython\users\views.py changed, reloading.
2021-04-19 16:30:15,776 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-19 16:31:11,635 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 C:\Users\user\Desktop\WallAppPython\users\views.py changed, reloading.
2021-04-19 16:31:12,656 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-19 16:32:21,322 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 C:\Users\user\Desktop\WallAppPython\users\views.py changed, reloading.
2021-04-19 16:32:22,347 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-19 16:32:50,323 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "POST /api/users/list/ HTTP/1.1" 201 1539
2021-04-19 16:33:24,089 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 C:\Users\user\Desktop\WallAppPython\users\views.py changed, reloading.
2021-04-19 16:33:25,100 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-19 17:27:35,520 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-19 17:27:46,355 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "POST /api/users/list/ HTTP/1.1" 201 1325
2021-04-19 17:28:08,013 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "POST /api/token/ HTTP/1.1" 200 469
2021-04-19 17:28:17,370 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "PUT /api/users/details/1/ HTTP/1.1" 201 1337
2021-04-19 17:28:44,083 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "GET /api/users/details/1/ HTTP/1.1" 200 1339
2021-04-19 17:30:49,263 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "POST /api/wall/walls/list/ HTTP/1.1" 201 274
2021-04-19 17:31:12,081 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "GET /api/wall/walls/list/ HTTP/1.1" 200 338
2021-04-19 17:31:20,884 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "GET /api/wall/walls/details/1/ HTTP/1.1" 200 276
2021-04-19 17:31:42,590 WARNING: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\log.py
	 Bad Request: /api/wall/comment/list/
2021-04-19 17:31:42,590 WARNING: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "POST /api/wall/comment/list/ HTTP/1.1" 400 76
2021-04-19 17:31:54,609 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "POST /api/wall/comment/list/ HTTP/1.1" 201 237
2021-04-19 17:32:20,659 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "GET /api/wall/likes/1/ HTTP/1.1" 200 60
2021-04-19 17:32:53,627 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "POST /api/users/list/ HTTP/1.1" 201 1325
2021-04-19 17:33:18,556 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "POST /api/token/ HTTP/1.1" 200 469
2021-04-19 17:33:27,904 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "GET /api/wall/likes/1/ HTTP/1.1" 200 61
2021-04-19 17:33:53,334 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "GET /api/wall/walls/details/1/ HTTP/1.1" 200 451
2021-04-19 17:35:12,128 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "GET /api/wall/likes/1/ HTTP/1.1" 200 60
2021-04-19 17:35:45,363 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "POST /api/token/ HTTP/1.1" 200 470
2021-04-19 17:35:53,393 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "GET /api/wall/likes/1/ HTTP/1.1" 200 60
2021-04-19 17:36:20,992 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "GET /api/wall/walls/details/1/ HTTP/1.1" 200 451
2021-04-19 17:36:32,892 ERROR: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\log.py
	 Internal Server Error: /api/wall/dislikes/1/
Traceback (most recent call last):
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\handlers\base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\handlers\base.py", line 143, in _get_response
    response = response.render()
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\rest_framework\renderers.py", line 100, in render
    ret = json.dumps(
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 234, in dumps
    return cls(
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type property is not JSON serializable
2021-04-19 17:36:32,895 ERROR: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "GET /api/wall/dislikes/1/ HTTP/1.1" 500 104094
2021-04-19 17:37:48,153 ERROR: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\log.py
	 Internal Server Error: /api/wall/dislikes/1/
Traceback (most recent call last):
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\handlers\base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\handlers\base.py", line 143, in _get_response
    response = response.render()
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\rest_framework\renderers.py", line 100, in render
    ret = json.dumps(
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\rest_framework\utils\json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 234, in dumps
    return cls(
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\rest_framework\utils\encoders.py", line 67, in default
    return super().default(obj)
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type property is not JSON serializable
2021-04-19 17:37:48,156 ERROR: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "GET /api/wall/dislikes/1/ HTTP/1.1" 500 104061
2021-04-19 17:39:01,342 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 E:\Pycharm Project\viral_exam\WallAppPython\wall\views.py changed, reloading.
2021-04-19 17:39:02,508 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\utils\autoreload.py
	 Watching for file changes with StatReloader
2021-04-19 17:39:05,761 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "GET /api/wall/dislikes/1/ HTTP/1.1" 200 64
2021-04-19 17:39:21,639 INFO: E:\Pycharm Project\WallAppPython-master\venv\lib\site-packages\django\core\servers\basehttp.py
	 "GET /api/wall/walls/details/1/ HTTP/1.1" 200 451
